services:
  - type: web
    name: pdf-management-app
    env: python
    buildCommand: "pip install -r requirements.txt && python scripts/init_database.py"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: pdf-storage
      mountPath: /app/static/pdfs
      sizeGB: 1
